FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

COPY requirements-bot.txt .

RUN pip install --no-cache-dir -r requirements-bot.txt

COPY bot.py .

CMD ["python", "bot.py"]