services:
  model-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: yolo-model-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./model:/app/model:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped

  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: yolo-tg-bot
    env_file:
      - .env
    environment:
      - MODEL_API_URL=http://model-api:5000
    depends_on:
      - model-api
    restart: unless-stopped

#  tunnel:
#    image: cloudflare/cloudflared:latest
#    container_name: yolo-cloudflare-tunnel
#    command: tunnel --no-autoupdate --protocol http2 --url http://model-api:5000
#    depends_on:
#      - model-api
#    restart: unless-stopped